/* Gym Hero — Comment exécuter chaque exercice.
   Les photos viennent de free-exercise-db (domaine public, licence Unlicense),
   servies par CDN et mises en cache au fil des consultations : voir sw.js.
   `img` est le dossier de l'exercice dans cette base. */

const DEMO_BASE = 'https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/';

const EXERCISE_GUIDE = {
  leg_press: { img: "Leg_Press", how: ["Cale le dos et le bassin contre le dossier, pieds à largeur d'épaules au milieu du plateau.", "Descends jusqu'à environ 90° au genou, puis pousse par les talons sans verrouiller les genoux en haut."], tip: "Le bas du dos ne doit jamais décoller : si le bassin s'enroule, tu descends trop bas." },
  leg_curl: { img: "Lying_Leg_Curls", how: ["Chevilles sous le rouleau, genoux alignés avec l'axe de la machine.", "Ramène les talons vers les fessiers, marque un temps d'arrêt, puis reviens lentement."], tip: "Garde le bassin collé : si tu décolles les hanches, la charge est trop lourde." },
  leg_extension: { img: "Leg_Extensions", how: ["Assieds-toi au fond, rouleau posé sur le bas des tibias.", "Tends les jambes jusqu'à l'horizontale, serre les quadriceps une seconde, redescends en contrôlant."], tip: "Évite le à-coup en fin de mouvement : c'est le genou qui encaisse." },
  hip_abductor: { img: "Thigh_Abductor", how: ["Assis, dos calé, genoux contre les coussins intérieurs.", "Écarte les cuisses vers l'extérieur au maximum confortable, puis reviens lentement."], tip: "Penche très légèrement le buste en avant pour mieux cibler le moyen fessier." },
  hip_adductor: { img: "Thigh_Adductor", how: ["Assis, dos calé, genoux contre les coussins extérieurs, cuisses écartées.", "Serre les cuisses jusqu'à les rapprocher, marque l'arrêt, puis laisse repartir en contrôlant."], tip: "N'ouvre pas plus que ta souplesse ne le permet : l'étirement doit rester indolore." },
  hack_squat: { img: "Hack_Squat", how: ["Épaules sous les coussins, pieds à mi-plateau, largeur d'épaules.", "Descends jusqu'à cuisses parallèles, puis remonte en poussant dans tout le pied."], tip: "Genoux dans l'axe des pieds, jamais rentrés vers l'intérieur." },
  calf_raise: { img: "Standing_Calf_Raises", how: ["Avant-pieds sur la marche, talons dans le vide, jambes tendues.", "Monte le plus haut possible sur la pointe, puis descends jusqu'à sentir l'étirement."], tip: "Mouvement lent : les mollets ne répondent pas aux rebonds." },
  calf_seated: { img: "Seated_Calf_Raise", how: ["Assis, avant-pieds sur le repose-pied, coussin sur le bas des cuisses.", "Monte sur la pointe, tiens une seconde, redescends complètement."], tip: "Genoux pliés : c'est le soléaire qui travaille, sous le jumeau." },
  glute_bridge: { img: "Barbell_Hip_Thrust", how: ["Haut du dos appuyé sur un banc, barre sur les hanches, pieds à plat.", "Pousse le bassin vers le haut jusqu'à l'alignement cuisses-tronc, serre les fessiers, redescends."], tip: "Rentre légèrement le menton et les côtes pour ne pas cambrer." },
  squat: { img: "Barbell_Squat", how: ["Barre sur les trapèzes, pieds largeur d'épaules, pointes légèrement ouvertes.", "Descends en poussant les hanches vers l'arrière jusqu'à cuisses parallèles, puis remonte."], tip: "Regard devant, poitrine haute : dès que le buste s'écroule, arrête la série." },
  front_squat: { img: "Front_Barbell_Squat", how: ["Barre posée sur les deltoïdes avant, coudes hauts, poitrine ouverte.", "Descends bien droit, buste vertical, puis remonte en poussant dans les talons."], tip: "Si les coudes tombent, la barre glisse : garde-les hauts du début à la fin." },
  deadlift: { img: "Barbell_Deadlift", how: ["Barre contre les tibias, dos plat, hanches plus hautes que les genoux.", "Pousse le sol avec les jambes, la barre longe les cuisses, termine hanches tendues."], tip: "Le dos ne s'arrondit jamais. Le mouvement démarre par les jambes, pas par le dos." },
  rdl: { img: "Romanian_Deadlift", how: ["Debout, barre contre les cuisses, genoux à peine fléchis.", "Pousse les hanches vers l'arrière en gardant le dos plat, descends jusqu'à l'étirement des ischios, remonte."], tip: "Ce n'est pas un squat : les genoux bougent très peu, ce sont les hanches qui reculent." },
  lunge: { img: "Dumbbell_Lunges", how: ["Debout, un haltère dans chaque main, buste droit.", "Fais un grand pas en avant, descends jusqu'à ce que le genou arrière frôle le sol, repousse pour revenir."], tip: "Le genou avant reste au-dessus du pied, il ne part pas devant les orteils." },
  bulgarian: { img: "Split_Squat_with_Dumbbells", how: ["Pied arrière posé sur un banc, pied avant assez loin devant.", "Descends verticalement jusqu'à cuisse avant parallèle, puis repousse."], tip: "Tout le poids sur la jambe avant : la jambe arrière ne sert qu'à l'équilibre." },
  goblet_squat: { img: "Goblet_Squat", how: ["Un haltère tenu verticalement contre la poitrine, coudes rentrés.", "Descends entre les genoux, buste droit, puis remonte."], tip: "Idéal pour apprendre le squat : le poids devant t'oblige à rester droit." },
  step_up: { img: "Dumbbell_Step_Ups", how: ["Un haltère dans chaque main, face à un banc à hauteur de genou.", "Monte en poussant uniquement avec la jambe posée sur le banc, puis redescends en contrôlant."], tip: "Ne prends pas d'élan avec la jambe au sol, sinon l'exercice perd tout intérêt." },
  bench_press: { img: "Barbell_Bench_Press_-_Medium_Grip", how: ["Allongé, pieds au sol, omoplates serrées, mains un peu plus larges que les épaules.", "Descends la barre au niveau des tétons en contrôlant, puis pousse jusqu'à bras tendus."], tip: "Les coudes à environ 45° du corps, pas écartés à 90° : c'est l'épaule qui souffre." },
  incline_bench: { img: "Barbell_Incline_Bench_Press_-_Medium_Grip", how: ["Banc incliné à 30-45°, même prise que le développé couché.", "Descends la barre vers le haut des pectoraux, puis pousse."], tip: "Au-delà de 45°, ce sont les épaules qui prennent le relais sur les pectoraux." },
  db_bench: { img: "Dumbbell_Bench_Press", how: ["Allongé, un haltère dans chaque main au niveau de la poitrine, paumes vers l'avant.", "Pousse vers le haut sans cogner les haltères, puis redescends jusqu'à l'étirement."], tip: "Amplitude plus grande qu'à la barre : c'est tout l'intérêt, profites-en." },
  db_incline: { img: "Incline_Dumbbell_Press", how: ["Banc à 30-45°, haltères au niveau du haut des pectoraux.", "Pousse vers le haut et légèrement vers l'intérieur, puis redescends."], tip: "" },
  chest_press: { img: "Machine_Bench_Press", how: ["Assis, dos calé, poignées à hauteur de poitrine.", "Pousse jusqu'à bras presque tendus, puis reviens en contrôlant."], tip: "Règle la hauteur du siège pour que les poignées soient au niveau des tétons." },
  pec_deck: { img: "Butterfly", how: ["Assis, dos plaqué, avant-bras contre les coussins, coudes à hauteur d'épaules.", "Rapproche les bras devant toi, serre une seconde, puis laisse repartir lentement."], tip: "L'ouverture s'arrête quand tu sens l'étirement, pas au-delà." },
  cable_fly: { img: "Cable_Crossover", how: ["Debout entre deux poulies hautes, un pas en avant, buste légèrement penché.", "Ramène les mains devant toi en arc de cercle, bras quasi tendus, puis reviens."], tip: "Garde un léger angle au coude, figé pendant tout le mouvement." },
  dips: { img: "Dips_-_Chest_Version", how: ["Aux barres parallèles, bras tendus, buste penché en avant.", "Descends jusqu'à ce que les épaules soient au niveau des coudes, puis remonte."], tip: "Buste penché = pectoraux. Buste vertical = triceps." },
  pushup: { img: "Pushups", how: ["Mains un peu plus larges que les épaules, corps gainé en ligne droite.", "Descends la poitrine vers le sol, coudes à 45°, puis repousse."], tip: "Le bassin ne s'affaisse pas : serre fessiers et abdos." },
  pullup: { img: "Pullups", how: ["Suspendu, prise pronation un peu plus large que les épaules.", "Tire les coudes vers le bas jusqu'à passer le menton au-dessus de la barre, redescends en contrôlant."], tip: "Commence par abaisser les épaules : si tu tires d'abord avec les bras, le dos ne travaille pas." },
  lat_pulldown: { img: "Wide-Grip_Lat_Pulldown", how: ["Cuisses bloquées sous les coussins, prise large en pronation.", "Tire la barre vers le haut de la poitrine en sortant le torse, puis remonte en contrôlant."], tip: "Devant la tête, jamais derrière la nuque." },
  seated_row: { img: "Seated_Cable_Rows", how: ["Assis, pieds calés, dos droit, bras tendus vers la poulie.", "Tire la poignée vers le nombril en serrant les omoplates, puis reviens sans t'affaisser."], tip: "Le buste reste quasi immobile : ce sont les bras et les omoplates qui bougent." },
  barbell_row: { img: "Bent_Over_Barbell_Row", how: ["Buste penché à environ 45°, dos plat, barre sous les épaules.", "Tire la barre vers le nombril, coudes près du corps, puis redescends."], tip: "Si tu dois donner un coup de reins, allège." },
  db_row: { img: "One-Arm_Dumbbell_Row", how: ["Un genou et une main sur le banc, dos plat, haltère bras tendu.", "Tire l'haltère vers la hanche, coude le long du corps, puis redescends en étirant."], tip: "Ne tourne pas le buste pour tricher : les épaules restent parallèles au sol." },
  t_bar_row: { img: "Lying_T-Bar_Row", how: ["Buste penché, poitrine contre le support, poignées en main.", "Tire vers le torse en serrant les omoplates, puis reviens."], tip: "" },
  machine_row: { img: "Seated_Cable_Rows", how: ["Assis, poitrine contre le support, poignées bras tendus.", "Tire vers toi en rapprochant les omoplates, puis reviens en contrôlant."], tip: "" },
  pullover: { img: "Bent-Arm_Dumbbell_Pullover", how: ["Allongé en travers d'un banc, un haltère tenu à deux mains au-dessus de la poitrine.", "Descends l'haltère derrière la tête bras semi-tendus, puis ramène-le au-dessus de toi."], tip: "Descends seulement jusqu'à l'étirement confortable de l'épaule." },
  shrug: { img: "Dumbbell_Shrug", how: ["Debout, un haltère dans chaque main le long du corps, bras tendus.", "Hausse les épaules le plus haut possible, tiens une seconde, puis relâche."], tip: "Ne fais pas de rotation des épaules : c'est un mouvement de bas en haut." },
  back_extension: { img: "Hyperextensions_Back_Extensions", how: ["Hanches sur le coussin, chevilles bloquées, corps aligné.", "Descends le buste en gardant le dos plat, puis remonte jusqu'à l'alignement."], tip: "Ne remonte pas plus haut que l'alignement : inutile de se cambrer." },
  face_pull: { img: "Face_Pull", how: ["Poulie à hauteur de visage, corde en prise neutre, bras tendus.", "Tire la corde vers le front en écartant les mains, coudes hauts, puis reviens."], tip: "Excellent pour compenser tout le travail de poussée : coudes au niveau des épaules." },
  ohp: { img: "Standing_Military_Press", how: ["Debout, barre au niveau des clavicules, mains un peu plus larges que les épaules.", "Pousse la barre au-dessus de la tête, puis redescends aux clavicules."], tip: "Serre fessiers et abdos pour ne pas cambrer le bas du dos." },
  db_shoulder: { img: "Dumbbell_Shoulder_Press", how: ["Assis dossier haut, haltères à hauteur d'oreilles, paumes vers l'avant.", "Pousse vers le haut sans verrouiller brutalement, puis redescends."], tip: "" },
  lateral_raise: { img: "Side_Lateral_Raise", how: ["Debout, un haltère dans chaque main le long du corps, léger angle au coude.", "Monte les bras sur les côtés jusqu'à l'horizontale, puis redescends lentement."], tip: "Pas plus haut que les épaules, et sans élan : c'est un exercice léger." },
  front_raise: { img: "Front_Dumbbell_Raise", how: ["Debout, haltères devant les cuisses, paumes vers toi.", "Monte un bras devant toi jusqu'à l'horizontale, redescends, puis alterne."], tip: "" },
  rear_delt_fly: { img: "Reverse_Flyes", how: ["Buste penché en avant, haltères sous la poitrine, coudes légèrement fléchis.", "Écarte les bras sur les côtés en serrant les omoplates, puis reviens."], tip: "Charges légères : ce muscle est petit, la technique prime." },
  upright_row: { img: "Upright_Barbell_Row", how: ["Debout, barre devant les cuisses, prise largeur d'épaules.", "Tire la barre vers le menton en gardant les coudes plus hauts que les mains."], tip: "Si tu ressens un pincement dans l'épaule, élargis la prise ou change d'exercice." },
  barbell_curl: { img: "Barbell_Curl", how: ["Debout, barre en supination, bras le long du corps.", "Fléchis les coudes jusqu'en haut, puis redescends en contrôlant jusqu'à bras tendus."], tip: "Les coudes restent collés au corps : s'ils avancent, ce sont les épaules qui aident." },
  db_curl: { img: "Dumbbell_Bicep_Curl", how: ["Debout, un haltère dans chaque main, paumes vers l'avant.", "Monte en fléchissant le coude, redescends complètement, puis alterne ou fais les deux ensemble."], tip: "" },
  hammer_curl: { img: "Hammer_Curls", how: ["Debout, haltères en prise neutre, pouces vers le haut.", "Monte sans tourner le poignet, puis redescends."], tip: "Cette prise cible le brachial : c'est lui qui donne l'épaisseur au bras." },
  preacher_curl: { img: "Preacher_Curl", how: ["Bras posés sur le pupitre, aisselles calées contre le haut.", "Monte jusqu'à contraction, puis redescends lentement sans tendre brutalement."], tip: "Ne lâche jamais la descente : c'est là que le biceps s'étire le plus." },
  cable_curl: { img: "Standing_Biceps_Cable_Curl", how: ["Debout face à la poulie basse, barre ou poignée en supination.", "Fléchis les coudes, serre en haut, puis redescends en gardant la tension."], tip: "" },
  triceps_pushdown: { img: "Triceps_Pushdown", how: ["Face à la poulie haute, coudes collés au corps, avant-bras à l'horizontale.", "Tends les bras vers le bas, serre le triceps, puis remonte sans décoller les coudes."], tip: "Seuls les avant-bras bougent. Le buste reste immobile." },
  skull_crusher: { img: "Lying_Triceps_Press", how: ["Allongé, barre au-dessus du front, bras tendus.", "Fléchis les coudes pour descendre la barre vers le front, puis retends les bras."], tip: "Les bras restent verticaux : seuls les coudes se plient." },
  overhead_ext: { img: "Standing_Dumbbell_Triceps_Extension", how: ["Debout ou assis, un haltère tenu à deux mains au-dessus de la tête.", "Descends l'haltère derrière la nuque en gardant les coudes hauts, puis retends."], tip: "Coudes serrés vers l'intérieur, ils ne doivent pas s'écarter." },
  close_grip: { img: "Close-Grip_Barbell_Bench_Press", how: ["Allongé, mains écartées de la largeur des épaules sur la barre.", "Descends la barre vers le bas de la poitrine, coudes près du corps, puis pousse."], tip: "Ne serre pas plus que la largeur d'épaules : les poignets n'aiment pas." },
  wrist_curl: { img: "Palms-Up_Barbell_Wrist_Curl_Over_A_Bench", how: ["Avant-bras posés sur les cuisses ou un banc, paumes vers le haut, poignets dans le vide.", "Enroule les poignets vers le haut, puis laisse redescendre complètement."], tip: "" },
  plank: { img: "Plank", how: ["En appui sur les avant-bras et les pointes de pieds, corps aligné.", "Tiens la position en serrant abdos et fessiers, respiration normale."], tip: "Bassin ni haut ni affaissé : imagine une planche de la tête aux talons." },
  crunch: { img: "Crunches", how: ["Allongé, genoux fléchis, mains sur les tempes sans tirer sur la nuque.", "Décolle les omoplates en enroulant le buste, puis redescends sans poser la tête."], tip: "L'amplitude est courte : c'est normal, inutile de monter jusqu'aux genoux." },
  cable_crunch: { img: "Cable_Crunch", how: ["À genoux face à la poulie haute, corde de part et d'autre de la tête.", "Enroule le buste vers le sol en contractant les abdos, puis remonte."], tip: "C'est le dos qui s'arrondit, pas les hanches qui reculent." },
  leg_raise: { img: "Hanging_Leg_Raise", how: ["Suspendu à la barre ou allongé au sol, jambes tendues.", "Monte les jambes en enroulant le bassin, puis redescends en contrôlant."], tip: "Le mouvement part du bassin : sans enroulement, ce sont les fléchisseurs de hanche qui travaillent." },
  russian_twist: { img: "Russian_Twist", how: ["Assis, buste incliné en arrière, pieds décollés, poids à deux mains.", "Tourne le buste d'un côté puis de l'autre en accompagnant avec le regard."], tip: "" },
  ab_machine: { img: "Ab_Crunch_Machine", how: ["Assis, poignées en main, dos calé.", "Enroule le buste vers l'avant en contractant les abdos, puis reviens en contrôlant."], tip: "" },
  side_plank: { img: "Side_Bridge", how: ["En appui sur un avant-bras et le côté du pied, corps aligné.", "Monte les hanches et tiens la position, puis change de côté."], tip: "Les hanches ne doivent pas reculer : reste bien dans un seul plan." },
  treadmill: { img: "Walking_Treadmill", how: ["Règle la vitesse et la pente, puis marche ou cours en gardant le buste droit.", "Ne t'accroche pas aux barres : ça fausse l'effort et la posture."], tip: "En pente forte, la marche vaut largement la course pour les fessiers." },
  bike: { img: "Bicycling_Stationary", how: ["Règle la selle : jambe presque tendue en bas de la pédale.", "Pédale à cadence régulière, dos droit, épaules relâchées."], tip: "" },
  elliptical: { img: "Elliptical_Trainer", how: ["Pieds à plat sur les pédales, mains sur les poignées mobiles.", "Mouvement fluide et régulier, buste droit, sans t'appuyer sur les bras."], tip: "Sans impact pour les articulations : idéal en récupération." },
  rower: { img: "Rowing_Stationary", how: ["Cale les pieds, saisis la poignée, jambes fléchies, bras tendus.", "Pousse d'abord avec les jambes, puis penche le buste, puis tire avec les bras. Reviens dans l'ordre inverse."], tip: "L'ordre jambes-buste-bras est essentiel, sinon le dos encaisse tout." },
  stairmaster: { img: "Stairmaster", how: ["Monte les marches à rythme régulier, buste droit.", "Pose le pied entier sur la marche, pas seulement la pointe."], tip: "Ne te suspends pas aux rampes, tu diviserais l'effort par deux." },
  jump_rope: { img: "Rope_Jumping", how: ["Corde derrière les talons, coudes près du corps.", "Saute juste assez haut pour laisser passer la corde, en amortissant sur l'avant du pied."], tip: "Ce sont les poignets qui tournent, pas les bras." }
};

/** Les deux photos d'un exercice : position de départ et position finale. */
function demoImages(exId) {
  const g = EXERCISE_GUIDE[exId];
  return g ? [DEMO_BASE + g.img + '/0.jpg', DEMO_BASE + g.img + '/1.jpg'] : null;
}
function exerciseGuide(exId) { return EXERCISE_GUIDE[exId] || null; }
